// Test generated by RoostGPT for test java-rest using AI Model gpt

package payroll;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class Employee_getRoleabaa33fdf6Test {

    @InjectMocks
    private Employee employee;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetRoleWhenRoleIsNotNull() {
        String expectedRole = "Developer";
        employee.setRole(expectedRole);
        String actualRole = employee.getRole();
        assertEquals(expectedRole, actualRole, "Role must be " + expectedRole);
    }

    @Test
    public void testGetRoleWhenRoleIsNull() {
        employee.setRole(null);
        String actualRole = employee.getRole();
        assertEquals(null, actualRole, "Role must be null");
    }
}
