// Test generated by RoostGPT for test java-rest using AI Model gpt

package payroll;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class EmployeeNotFoundAdvice_employeeNotFoundHandler0d6cd56f07Test {

    @InjectMocks
    EmployeeNotFoundAdvice employeeNotFoundAdvice;

    @Mock
    EmployeeNotFoundException ex;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testEmployeeNotFoundHandler_Success() {
        String expectedMessage = "Employee not found";
        when(ex.getMessage()).thenReturn(expectedMessage);
        String actualMessage = employeeNotFoundAdvice.employeeNotFoundHandler(ex);
        assertEquals(expectedMessage, actualMessage);
    }

    @Test
    public void testEmployeeNotFoundHandler_Null() {
        when(ex.getMessage()).thenReturn(null);
        String actualMessage = employeeNotFoundAdvice.employeeNotFoundHandler(ex);
        assertEquals(null, actualMessage);
    }
}
