// Test generated by RoostGPT for test java-rest using AI Model gpt

package payroll;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Employee_setNamea6b90133e4Test {

    private Employee employee;

    @BeforeEach
    public void setup() {
        employee = new Employee();
    }

    @Test
    public void testSetName_Success() {
        // Arrange
        String expectedName = "John Doe";

        // Act
        employee.setName(expectedName);

        // Assert
        assertEquals(expectedName, employee.getName(), "Employee name should be set correctly.");
    }

    @Test
    public void testSetName_Null() {
        // Arrange
        String expectedName = null;

        // Act
        employee.setName(expectedName);

        // Assert
        assertNull(employee.getName(), "Employee name should be null.");
    }
}
