// Test generated by RoostGPT for test java-rest using AI Model gpt

package payroll;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Employee_setId09de54ad49Test {

    @InjectMocks
    private Employee employee;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetIdSuccess() {
        Long expectedId = 123L;
        employee.setId(expectedId);
        assertEquals(expectedId, employee.getId(), "The ID set in the employee object should match the expected ID");
    }

    @Test
    public void testSetIdNull() {
        employee.setId(null);
        assertNull(employee.getId(), "The ID in the employee object should be null");
    }
}
