// Test generated by RoostGPT for test java-rest using AI Model gpt

package payroll;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Employee_getName7b14389168Test {

    @Mock
    private Employee employee;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetName_WhenNameIsJohn_ReturnsJohn() {
        // TODO: Replace "John" with the actual name of the employee
        when(employee.getName()).thenReturn("John");

        String name = employee.getName();

        assertEquals("John", name);
    }

    @Test
    public void testGetName_WhenNameIsNull_ReturnsNull() {
        when(employee.getName()).thenReturn(null);

        String name = employee.getName();

        assertEquals(null, name);
    }
}
